### ISSUE TITLE
Any tips on clearing the database up?

### ISSUE THREAD

**Issue by jasongrishkoff** [edemaine/kadira-compose#2]
I've noticed it start to get a bit sluggish. Someone in the Meteor forums suggested this:
https://forums.meteor.com/t/running-a-own-kadira-instance-update-now-with-a-guide/35938/170

Have you seen this with your own instance?  Any thoughts on how to do it via Docker?

**Comment by edemaine** [comment]
Try running `./docker-compose exec mongo mongo kadira` and then entering the `db` commands (with a more recent date).

I have noticed slowdown, sometimes even requiring a reboot of the server.  Not quite sure what the issue is, but I'll try this for a while.  Thanks!  If useful, I will turn it into a cron job...

**Comment by jasongrishkoff** [comment]
Cool yeah, just ran that query and things seem a bit faster now!

**Comment by edemaine** [comment]
I just added some tools (`flush-mongo` and `crontab`) for automating this!  Check out the new README, and let me know if you have any questions. Also, if you know a clean way of doing this purely in `docker-compose` instead of relying on an external `crontab`, let me know.
